name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            PrometheusClientNet/Prometheus.Client@master
            PrometheusClientNet/Prometheus.Client.DependencyInjection@master
            PrometheusClientNet/Prometheus.Client.HealthChecks@master
            PrometheusClientNet/Prometheus.Client.HttpRequestDurations@master
            PrometheusClientNet/Prometheus.Client.AspNetCore@master
            PrometheusClientNet/prom-tmpl@master
            PrometheusClientNet/Prometheus.Client.MetricPusher@master
            PrometheusClientNet/Prometheus.Client.MetricServer@master
          FILES: |
            root/LICENSE=LICENSE
            root/icon.png=icon.png
            root/Directory.Build.props=Directory.Build.props
            root/stylecop.json=stylecop.json
            root/.ruleset=.ruleset
            root/.editorconfig=.editorconfig
            root/.gitattributes=.gitattributes
            github/renovate.json=.github/renovate.json
          TOKEN: ${{ secrets.SYNC_FILES }}
