name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          GIT_EMAIL: cmt@phnx47.net
          GIT_USERNAME: Serge K
          COMMIT_MESSAGE: "chore: update file(s) from sync-files"
          FILE_PATTERNS: |
            ^\.$
          TARGET_REPOS: |
            PrometheusClientNet/prom-tmpl
          GITHUB_TOKEN: ${{ secrets.SYNC_FILES }}
          SRC_ROOT: /sync-root/
          TARGET_ROOT: /
