name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@master
        with:
          PULL_REQUEST_BRANCH_NAME: master
          REPOSITORIES: |
            prom-client-net/Prometheus.Client@sync-files
            prom-client-net/Prometheus.Client.DependencyInjection@sync-files
            prom-client-net/Prometheus.Client.HealthChecks@sync-files
            prom-client-net/Prometheus.Client.HttpRequestDurations@sync-files
            prom-client-net/Prometheus.Client.AspNetCore@sync-files
            prom-client-net/prom-tmpl@sync-files
            prom-client-net/Prometheus.Client.MetricPusher@sync-files
            prom-client-net/Prometheus.Client.MetricServer@sync-files
          FILES: |
            root/LICENSE=LICENSE
            root/icon.png=icon.png
            root/Directory.Build.props=Directory.Build.props
            root/stylecop.json=stylecop.json
            root/.ruleset=.ruleset
            root/.editorconfig=.editorconfig
            root/.gitattributes=.gitattributes
            github/renovate.json=.github/renovate.json
          TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
