name: File Sync

on:
  schedule: [{ cron: "15 */24 * * *" }]
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@master
        with:
          PULL_REQUEST_BRANCH_NAME: true
          REPOSITORIES: |
            PrometheusClientNet/Prometheus.Client
            PrometheusClientNet/Prometheus.Client.DependencyInjection
            PrometheusClientNet/Prometheus.Client.HealthChecks
            PrometheusClientNet/Prometheus.Client.HttpRequestDurations
            PrometheusClientNet/Prometheus.Client.AspNetCore
            PrometheusClientNet/prom-tmpl
            PrometheusClientNet/Prometheus.Client.MetricPusher
            PrometheusClientNet/Prometheus.Client.MetricServer
          FILES: |
            root/LICENSE=LICENSE
            root/icon.png=icon.png
            root/Directory.Build.props=Directory.Build.props
            root/stylecop.json=stylecop.json
            root/.ruleset=.ruleset
            root/.editorconfig=.editorconfig
            root/.gitattributes=.gitattributes
            github/renovate.json=.github/renovate.json
          TOKEN: ${{ secrets.SYNC_FILES }}
