name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            PrometheusClientNet/prom-tmpl@master
          FILES: |
            sync-root/LICENSE=LICENSE
            sync-root/icon.png=icon.png
            sync-root/Directory.Build.props=Directory.Build.props
            sync-root/stylecop.json=stylecop.json
            sync-root/.ruleset=.ruleset
            sync-root/.editorconfig=.editorconfig
            sync-root/.gitattributes=.gitattributes
          TOKEN: ${{ secrets.SYNC_FILES }}
