name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file-sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          GIT_EMAIL: cmt@phnx47.net
          GIT_USERNAME: Serge K
          COMMIT_MESSAGE: "chore: update file(s) from sync-files"
          FILE_PATTERNS: |
            ^LICENSE$
            ^icon.png$
            ^Directory.Build.props$
            ^stylecop.json$
            ^.ruleset$
          TARGET_REPOS: |
            PrometheusClientNet/Prometheus.Client
            PrometheusClientNet/Prometheus.Client.DependencyInjection
            PrometheusClientNet/Prometheus.Client.HealthChecks 
            PrometheusClientNet/Prometheus.Client.HttpRequestDurations
            PrometheusClientNet/Prometheus.Client.AspNetCore
            PrometheusClientNet/prom-tmpl
            PrometheusClientNet/Prometheus.Client.MetricPusher
            PrometheusClientNet/Prometheus.Client.MetricServer
          GITHUB_TOKEN: ${{ secrets.SYNC_FILES }}
